<a href="https://colab.research.google.com/github/itsmevishnu/python/blob/master/Learn_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(5+5)

10


- Print is the basic command to print the elements
- We can use expression, strings, numbers etc.

In [ ]:
x = 3
y = 1.2
z = True
a = 6+5j
print (type(a))                                                                  #complex number

<class 'complex'>


In [ ]:
a = [1,2,3,4,5,6,7,8]
print(a)
a[2:6] = [100, 101, 102, 103]

print(a)

[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 100, 101, 102, 103, 7, 8]


## Numpy
- Numpy is much faster because, it has a 8 bit integer, which is very faster to access
- Numpy is faster because, the memory allocation is contigious rather than different locations as Python list
- Numpy array can hold only one type of values at a time unlike python list
- Numpy is used for linear algebra, matrix , image processing, data science etc.


In [ ]:
import numpy as np

### One dimensional array
1. Creation of array using 
```python 
np.array([items..]) # creates a new array, need to pass the list of values
np.ones(n)  # creates a new array with ones, pass the number of 1s
np.zeros(n) # Creates a new array with zeros,pass the number of 0s
np.arange(start, end, step) # Creates an array starts from start, and ends at end-1 with steps with step.
np.linspace(start, end, n) # Creates an equally spaced array between start and end with n element
np.empty() # Creates an array. initially the values will be some random values
```
2. Accessing the elements
3. Slicing elements
4. Basic properties 
```python
arr.dtype # for the data type
arr.ndim # dimension of the array
arr.size # for the size of the array
arr.itemsize # for the size of one array item in bytes
arr.nbytes # total size of the array in bytes
```
5. Coversion to multiple dimension array

## 1. Creation of array

In [ ]:
a = np.array([1, 2, 3,4,5,6], dtype=np.int8) # we can assin the type here explicitly. 
b = np.array([2,3,5,6,], dtype=np.int32) # d.type is for showing the type of the data
c = np.array([1.23,3,4,5], dtype=float) #np.float is changed to float in the latest version of numpy

zero = np.zeros(3)
ones = np.ones(4)
empty = np.empty(2)
a_range = np.arange(1,10,2)
lin_space = np.linspace(1,10,5)


print(a)
print(b)
print(c)
print(zero)
print(ones)
print(empty)
print(a_range)
print(lin_space)

[1 2 3 4 5 6]
[2 3 5 6]
[1.23 3.   4.   5.  ]
[0. 0. 0.]
[1. 1. 1. 1.]
[1.9596952e-316 1.4821969e-323]
[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


## 4. Basic Properties

In [ ]:
print(a.ndim, a.shape)  # dimension of the array, shape of the given array
print(a.itemsize)# size (in byte) of each item in the array
print(a.size)# total size(len)  of the  array
print(a.nbytes) # itemsize*size --> provides the total size
print(a.dtype) # dtype stands for data type

1 (6,)
1
6
6
int8
